version: 0.0
os: linux 
files:
  - source: /
    destination: /opt/tomcat/apache-tomcat-8.0.53/webapps/api
file_exists_behavior: OVERWRITE
hooks:
  Install:
    - location: scripts/install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ubuntu
