version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo installing
  build:
    commands:
      - echo Build started on `date`
      - echo Gradle Build
      - chmod +x gradlew
      - sudo ./gradlew build
  post_build:
    commands:
      - echo build completed
artifacts:
  files:
    - appspec.yml
    - /build/libs/*.war
    - script/
    - '**/*'
